[package]
name = "companion-models"
version.workspace = true
edition.workspace = true

[dependencies]
companion-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
