use std::collections::HashMap;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::ids::{ArtifactId, EntityId, EventId, MemoryId, RelationshipId, TenantId, WorkspaceId};

// ---------------------------------------------------------------------------
// Memory Tier Hierarchy (L0 through L6)
// ---------------------------------------------------------------------------

/// The 7 functional storage tiers of the hierarchical memory subsystem.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryTier {
    /// L0 Hot: Active turn reasoning scratchpad and working state.
    Working,
    /// L1 Warm: Conversation turn history buffer and session transcripts.
    Session,
    /// L2 Warm: Past task trajectories, event summaries, and retrospectives.
    Episodic,
    /// L3 Cold: Long-term semantic knowledge chunks and vector embeddings.
    Semantic,
    /// L4 Cold: Knowledge graph entity-relationship triples.
    Relational,
    /// L5 Cold: Versioned procedural capabilities and successful workflows.
    Procedural,
    /// L6 Cold: Durable external work product references and evidence.
    Artifacts,
}

impl MemoryTier {
    /// Numerical level in the hierarchy (0 to 6).
    pub fn level(&self) -> u8 {
        match self {
            Self::Working => 0,
            Self::Session => 1,
            Self::Episodic => 2,
            Self::Semantic => 3,
            Self::Relational => 4,
            Self::Procedural => 5,
            Self::Artifacts => 6,
        }
    }
}

impl std::fmt::Display for MemoryTier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Working => write!(f, "L0:working"),
            Self::Session => write!(f, "L1:session"),
            Self::Episodic => write!(f, "L2:episodic"),
            Self::Semantic => write!(f, "L3:semantic"),
            Self::Relational => write!(f, "L4:relational"),
            Self::Procedural => write!(f, "L5:procedural"),
            Self::Artifacts => write!(f, "L6:artifacts"),
        }
    }
}

// ---------------------------------------------------------------------------
// Trust Classes & Memory Status
// ---------------------------------------------------------------------------

/// Trust and authority classification of a memory item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum TrustClass {
    /// Imported from potentially hostile or unverified external content.
    ExternalUntrusted,
    /// Generated by model inference / reasoning.
    #[default]
    AgentInferred,
    /// Extracted from an authorized project document or artifact.
    DocumentDerived,
    /// Directly confirmed by deterministic tool / verifier evidence.
    ToolVerified,
    /// Explicitly stated or confirmed by the human user.
    UserConfirmed,
}

impl TrustClass {
    /// Multiplicative trust weight used in multi-factor scoring (0.0 to 1.0).
    pub fn trust_weight(&self) -> f32 {
        match self {
            Self::UserConfirmed => 1.0,
            Self::ToolVerified => 0.9,
            Self::DocumentDerived => 0.7,
            Self::AgentInferred => 0.5,
            Self::ExternalUntrusted => 0.2,
        }
    }

    /// Numerical ranking for precedence during contradiction resolution (higher wins).
    pub fn authority_rank(&self) -> u8 {
        match self {
            Self::ExternalUntrusted => 1,
            Self::AgentInferred => 2,
            Self::DocumentDerived => 3,
            Self::ToolVerified => 4,
            Self::UserConfirmed => 5,
        }
    }
}

/// Lifecycle status of a memory record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum MemoryStatus {
    /// Active and available for retrieval.
    #[default]
    Active,
    /// Deprecated due to age or reduced relevance.
    Deprecated,
    /// Explicitly revoked or forgotten by policy / user command.
    Revoked,
    /// Replaced by a newer, higher-authority memory item.
    Superseded,
}

// ---------------------------------------------------------------------------
// Memory Item / Record
// ---------------------------------------------------------------------------

/// A discrete unit of stored memory across any hierarchical tier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryItem {
    pub memory_id: MemoryId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<TenantId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<WorkspaceId>,
    pub tier: MemoryTier,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    pub content: String,
    #[serde(default)]
    pub metadata: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embedding: Option<Vec<f32>>,
    pub importance: f32,
    pub confidence: f32,
    pub trust_class: TrustClass,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub last_accessed_at: DateTime<Utc>,
    pub access_count: u32,
    #[serde(default)]
    pub source_event_ids: Vec<EventId>,
    #[serde(default)]
    pub source_artifact_ids: Vec<ArtifactId>,
    #[serde(default)]
    pub supersedes: Vec<MemoryId>,
    pub status: MemoryStatus,
}

/// Alias for MemoryItem matching platform specification nomenclature.
pub type MemoryRecord = MemoryItem;

impl MemoryItem {
    pub fn new(tier: MemoryTier, content: impl Into<String>) -> Self {
        let now = Utc::now();
        Self {
            memory_id: MemoryId::new(),
            tenant_id: None,
            workspace_id: None,
            tier,
            subject: None,
            content: content.into(),
            metadata: serde_json::json!({}),
            embedding: None,
            importance: 1.0,
            confidence: 1.0,
            trust_class: TrustClass::AgentInferred,
            valid_from: Some(now),
            valid_to: None,
            created_at: now,
            updated_at: now,
            last_accessed_at: now,
            access_count: 0,
            source_event_ids: Vec::new(),
            source_artifact_ids: Vec::new(),
            supersedes: Vec::new(),
            status: MemoryStatus::Active,
        }
    }

    pub fn with_embedding(mut self, embedding: Vec<f32>) -> Self {
        self.embedding = Some(embedding);
        self
    }

    pub fn with_importance(mut self, importance: f32) -> Self {
        self.importance = importance.clamp(0.0, 5.0);
        self
    }

    pub fn with_confidence(mut self, confidence: f32) -> Self {
        self.confidence = confidence.clamp(0.0, 1.0);
        self
    }

    pub fn with_trust_class(mut self, trust_class: TrustClass) -> Self {
        self.trust_class = trust_class;
        self
    }

    pub fn with_subject(mut self, subject: impl Into<String>) -> Self {
        self.subject = Some(subject.into());
        self
    }

    pub fn with_tenant(mut self, tenant_id: TenantId) -> Self {
        self.tenant_id = Some(tenant_id);
        self
    }

    pub fn with_workspace(mut self, workspace_id: WorkspaceId) -> Self {
        self.workspace_id = Some(workspace_id);
        self
    }

    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = metadata;
        self
    }

    pub fn with_validity(mut self, valid_from: Option<DateTime<Utc>>, valid_to: Option<DateTime<Utc>>) -> Self {
        self.valid_from = valid_from;
        self.valid_to = valid_to;
        self
    }

    pub fn with_provenance(mut self, event_ids: Vec<EventId>, artifact_ids: Vec<ArtifactId>) -> Self {
        self.source_event_ids = event_ids;
        self.source_artifact_ids = artifact_ids;
        self
    }

    /// Mark this item as accessed (touch for recency and decay calculation).
    pub fn touch(&mut self) {
        self.last_accessed_at = Utc::now();
        self.access_count += 1;
    }

    /// Check if this memory is currently active and temporally valid.
    pub fn is_valid_at(&self, time: DateTime<Utc>) -> bool {
        if self.status != MemoryStatus::Active {
            return false;
        }
        if let Some(vf) = self.valid_from {
            if time + chrono::Duration::seconds(5) < vf {
                return false;
            }
        }
        if let Some(vt) = self.valid_to {
            if time > vt {
                return false;
            }
        }
        true
    }

    /// Supersede this memory record with a newer replacement.
    pub fn supersede_with(&mut self, new_record_id: MemoryId) {
        self.status = MemoryStatus::Superseded;
        self.updated_at = Utc::now();
        self.valid_to = Some(self.updated_at);
        if !self.supersedes.contains(&new_record_id) {
            self.supersedes.push(new_record_id);
        }
    }

    /// Calculate recency decay factor (1.0 for new/recent, approaching 0.0 over time).
    /// Uses exponential decay with a configurable half-life (default 30 days).
    pub fn recency_decay(&self, now: DateTime<Utc>, half_life_days: f32) -> f32 {
        let age_seconds = (now - self.last_accessed_at).num_seconds().max(0) as f32;
        let half_life_seconds = half_life_days * 86400.0;
        (-0.693147 * (age_seconds / half_life_seconds)).exp()
    }
}

// ---------------------------------------------------------------------------
// Knowledge Graph Entity & Triple
// ---------------------------------------------------------------------------

/// A named entity in the knowledge graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entity {
    pub entity_id: EntityId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<TenantId>,
    pub name: String,
    pub entity_type: String,
    #[serde(default)]
    pub attributes: HashMap<String, serde_json::Value>,
    pub confidence: f32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Entity {
    pub fn new(name: impl Into<String>, entity_type: impl Into<String>) -> Self {
        let now = Utc::now();
        Self {
            entity_id: EntityId::new(),
            tenant_id: None,
            name: name.into(),
            entity_type: entity_type.into(),
            attributes: HashMap::new(),
            confidence: 1.0,
            created_at: now,
            updated_at: now,
        }
    }

    pub fn with_attribute(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
        self.attributes.insert(key.into(), value);
        self.updated_at = Utc::now();
        self
    }
}

/// A semantic relationship triple: (subject) -[predicate]-> (object).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelationshipTriple {
    pub relationship_id: RelationshipId,
    pub subject: String,
    pub predicate: String,
    pub object: String,
    pub weight: f32,
    pub confidence: f32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_from: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valid_to: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

impl RelationshipTriple {
    pub fn new(subject: impl Into<String>, predicate: impl Into<String>, object: impl Into<String>) -> Self {
        let now = Utc::now();
        Self {
            relationship_id: RelationshipId::new(),
            subject: subject.into(),
            predicate: predicate.into(),
            object: object.into(),
            weight: 1.0,
            confidence: 1.0,
            valid_from: Some(now),
            valid_to: None,
            created_at: now,
        }
    }

    pub fn with_weight(mut self, weight: f32) -> Self {
        self.weight = weight;
        self
    }

    pub fn with_confidence(mut self, confidence: f32) -> Self {
        self.confidence = confidence;
        self
    }

    pub fn is_valid_at(&self, time: DateTime<Utc>) -> bool {
        if let Some(vf) = self.valid_from {
            if time + chrono::Duration::seconds(5) < vf {
                return false;
            }
        }
        if let Some(vt) = self.valid_to {
            if time > vt {
                return false;
            }
        }
        true
    }
}

// ---------------------------------------------------------------------------
// Memory Search & Filtering
// ---------------------------------------------------------------------------

/// Filter criteria for querying hierarchical memory.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MemoryFilter {
    pub tenant_id: Option<TenantId>,
    pub workspace_id: Option<WorkspaceId>,
    pub tier: Option<MemoryTier>,
    pub min_trust: Option<TrustClass>,
    pub min_importance: Option<f32>,
    pub active_only: bool,
    pub subject: Option<String>,
}

/// The result of querying memory across vector, graph, or episodic stores.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemorySearchResult {
    pub item: MemoryItem,
    pub score: f32,
    pub tier: MemoryTier,
    #[serde(default)]
    pub match_reasons: Vec<String>,
}

// ---------------------------------------------------------------------------
// Memory Consolidation (Dream Cycle) Report
// ---------------------------------------------------------------------------

/// Outcome summary produced by an offline Dream Cycle / Memory Consolidation run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsolidationReport {
    pub timestamp: DateTime<Utc>,
    pub duration_ms: u64,
    pub episodes_processed: usize,
    pub facts_extracted: usize,
    pub triples_created: usize,
    pub contradictions_resolved: usize,
    pub records_superseded: usize,
    pub skills_synthesized: usize,
}
